data:
  dataset: "PLACENTAL"
  seed: 2000
  label_min_max: [0.001, 0.999]
  num_classes: 4
  num_workers: 2 # Reduced from 8 for lower memory usage
  dataroot: "./dataset/"
  traindata: "./dataset/ultrasound_train_list.pkl"
  testdata: "./dataset/ultrasound_test_list.pkl"

model:
  type: "simple"
  data_dim: 150528
  #data_dim: 442368
  #    data_dim: [3, 32, 32]
  n_input_channels: 3
  n_input_padding: 0
  feature_dim: 2048 # Reduced from 6144 for memory efficiency
  hidden_dim: 2048 # Reduced from 6144 for memory efficiency
  cat_x: True
  cat_y_pred: True
  arch: resnet18 # Keep resnet18 instead of resnet50 for lower memory
  #    arch: resnet50
  #    arch: resnet18
  var_type: fixedlarge
  ema_rate: 0.9999
  ema: True
  num_k: 6

diffusion:
  beta_schedule: linear # cosine_anneal, cosine
  beta_start: 0.0001
  beta_end: 0.02
  timesteps: 1000
  test_timesteps: 100
  vis_step: 100
  num_figs: 10
  include_guidance: True # concat y_t with aux pred as eps_theta input
  apply_aux_cls: True
  #trained_aux_cls_ckpt_path: "/data/classification/pretrained/cifar10_ckpt"
  #    trained_aux_cls_ckpt_name: "snapshot_supervised.ckpt"
  #trained_aux_cls_ckpt_name: "snapshot_self_supervised.ckpt"
  aux_cls:
    arch: resnet18_ckpt # lenet5
    pre_train: True
    joint_train: True
    n_pretrain_epochs: 10
    logging_interval: 1

training:
  batch_size: 4 # Reduced from 64 for 4GB GPU
  n_epochs: 5
  warmup_epochs: 1
  add_t0_loss: False
  n_steps_req_grad: 100
  n_minibatches_add_ce: 20
  n_ce_epochs_warmup: 10
  n_ce_epochs_interval: 50
  n_sanity_check_epochs_freq: 500
  snapshot_freq: 1000000000
  logging_freq: 300 # Reduced logging frequency
  validation_freq: 10
  #lambda_ce: 0.01
  image_folder: "training_image_samples"
  gradient_accumulation_steps: 16 # To simulate batch size of 64 (4*16)

sampling:
  batch_size: 4 # Reduced from 64 for 4GB GPU
  sampling_size: 100 # Reduced from 1000 for faster testing
  last_only: True
  image_folder: "sampling_image_samples"

testing:
  batch_size: 4 # Reduced from 64 for 4GB GPU
  sampling_size: 100 # Reduced from 1000 for faster testing
  last_only: True
  plot_freq: 50 # Reduced from 200 for more frequent plotting
  image_folder: "testing_image_samples"
  n_samples: 50 # Reduced from 100
  n_bins: 10
  compute_metric_all_steps: False
  metrics_t: 0
  ttest_alpha: 0.05
  trimmed_mean_range: [0.0, 100.0]
  PICP_range: [2.5, 97.5]
  make_plot: True
  squared_plot: True
  plot_true: True
  plot_gen: True
  fig_size: [6, 4] # Reduced figure size

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: False
  eps: 0.00000001
  grad_clip: 1.0
  lr_schedule: True
  min_lr: 0.0

aux_optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: True
  eps: 0.00000001
  grad_clip: 1.0
